name: cuda-python-docs
channels:
  - conda-forge
dependencies:
  - cython=0.29.23
  - myst-parser
  - numpy
  - numpydoc
  - pip
  - pydata-sphinx-theme
  - pytest
  - scipy
  - sphinx
  - pip:
    - furo
    - myst-nb
    - enum-tools
    - sphinx_toolbox
